import pandas as pd
df = pd.read_csv("data/heart.csv")
# print("\n ---------- First 5 rows --------\n")
# print(df.head())
# print("\n ---------- Last 5 rows --------\n")
# print(df.tail())
# print("\n ---------- Dataset Shape --------\n")
# print(df.shape)
# print("\n ---------- Column Names --------\n")
# print(df.columns)
# print("\n ---------- data types --------\n")
# print(df.dtypes)
# print("\n ---------- dataset info --------\n")
# print(df.info)
# print("\n ---------- statistical summary --------\n")
# print(df.describe())
# print("\n ---------- missing values --------\n")
# print(df.isnull().sum())
# print("\n ---------- duplicate rows --------\n")
# print(df.duplicated().sum())
# print(df.columns.tolist())
print(df.dtypes)